version: '3.8'

services:
  app:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 order.wsgi
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    restart: 'on-failure'
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - app
    restart: 'on-failure'
volumes:
  staticfiles:
  media: